In [25]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [26]:
arr1 = np.arange(9).reshape(3,3)

arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [28]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
ser1 = Series([0,1,2],index=['T','U','V'])

ser2 = Series([3,4],index=['X','Y'])

In [30]:
ser1

T    0
U    1
V    2
dtype: int64

In [31]:
ser2

X    3
Y    4
dtype: int64

In [32]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [33]:
pd.concat([ser1,ser2], axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [34]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])


cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64